function Fi = compute_morison(mesh,p,waves)

Fi = computeMorisonForces( mesh.elemZ, ...
                           numel(waves.omegaVec), ...
                           waves.omegaVec, ...
                           waves.A_m, ...
                           waves.phi, ...
                           waves.k_m_vec, ...
                           mesh.sectionCut, ...
                           7,7, ...         % diameters
                           1.0,2.0,1025, ... % Cd,Cm,rho
                           waves.time, ...
                           mesh.h, p.Hs, p.Tp, ...
                           mesh.Le, false, true );
